export const RELAY_REGIONS = [
  {
    id: 1,
    region: 'Australia, New Zealand & South Pacific',
    shortName: 'Sydney',
    hubs: 'Sydney Hub',
    city: 'Sydney, Australia',
    timezone: 'Australia/Sydney',
    utcOffset: 'UTC+10',
    code: 'OCN-01',
    lat: -33.8688,
    lng: 151.2093,
    theme: 'Indigenous wisdom, planetary stewardship and compassionate futures',
    coordinator: 'Jeniffer Jerald JN',
    producer: {
      name: 'Producer Spot Available',
      role: 'Regional Producer — Oceania & Pacific',
      bio: 'Open convener and regional leadership spot to unite marine ecologists, indigenous guardians, and AI researchers exploring regenerative intelligence across the Pacific and Oceania.',
      img: '',
      tags: ['Regenerative AI', 'Ocean Health', 'Sydney Hub'],
      available: true,
    },
    accent: '#163B32',
  },
  {
    id: 2,
    region: 'Japan, Korea, Taiwan & Northeast Asia',
    shortName: 'Kyoto',
    hubs: 'Kyoto Hub',
    city: 'Kyoto, Japan',
    timezone: 'Asia/Tokyo',
    utcOffset: 'UTC+9',
    code: 'JPN-02',
    lat: 35.0116,
    lng: 135.7681,
    theme: 'Planet-centered AI, education, robotics and intergenerational responsibility',
    coordinator: 'Kavya',
    producer: {
      name: 'Jun Suto',
      role: 'Regional Producer — Kyoto',
      bio: 'Jun anchors the Kyoto dialogue exploring how ancient Japanese concepts of Futokoro (懐) and Wa (和) inform compassionate autonomous systems, robotics, and intergenerational responsibility (Speaker: Prof. Tomohiro Ishizu).',
      img: '/jun.png',
      tags: ['Futokoro Philosophy', 'Compassionate Robotics', 'Kyoto Hub'],
    },
    accent: '#C96F4A',
  },
  {
    id: 3,
    region: 'Southeast Asia',
    shortName: 'Singapore',
    hubs: 'Youth Hub (Singapore)',
    city: 'Singapore',
    timezone: 'Asia/Singapore',
    utcOffset: 'UTC+8',
    code: 'SEA-03',
    lat: 1.3521,
    lng: 103.8198,
    theme: 'Youth & AI+Compassion',
    coordinator: 'Jeniffer Jerald JN',
    producer: {
      name: 'Aditi Singh',
      role: 'Regional Producer — Southeast Asia (Youth Hub)',
      bio: 'Aditi leads youth-empowered initiatives across Southeast Asia, fostering grassroots AI literacy, digital agency, and compassionate planet-centered technologies for the next generation.',
      img: '/aditi.jpg',
      tags: ['Youth Leadership', 'Digital Inclusion', 'Youth Hub'],
    },
    accent: '#557C8B',
  },
  {
    id: 4,
    region: 'South Asia',
    shortName: 'Thiruvananthapuram',
    hubs: 'Thiruvananthapuram Hub',
    city: 'Thiruvananthapuram, India',
    timezone: 'Asia/Kolkata',
    utcOffset: 'UTC+5:30',
    code: 'IND-04',
    lat: 8.5241,
    lng: 76.9366,
    theme: 'AI for social impact, youth opportunity, health',
    coordinator: 'Kavya',
    producer: {
      name: 'Deepu S Nath',
      role: 'Regional Producer — South Asia',
      bio: 'Deepu leads grassroots technology and community education initiatives across South Asia, connecting youth ecosystems with compassionate, planet-centered AI architectures.',
      img: '/deepu.png',
      tags: ['Grassroots Tech', 'Youth Ecosystems', 'Kerala Hub'],
    },
    accent: '#C9A96A',
  },
  {
    id: 5,
    region: 'Middle East, Caucasus & Central Asia',
    shortName: 'Dubai',
    hubs: 'Dubai Hub',
    city: 'Dubai, UAE',
    timezone: 'Asia/Dubai',
    utcOffset: 'UTC+4',
    code: 'GCC-05',
    lat: 25.2048,
    lng: 55.2708,
    theme: 'Long-horizon governance, coexistence, peacebuilding and future cities',
    coordinator: 'Ann Rose Mathew',
    producer: {
      name: 'Walied Albasheer',
      role: 'Regional Producer — Middle East, Caucasus & Central Asia',
      bio: 'Walied leads the regional dialogue across the GCC and beyond on planet-centered AI governance, coexistence, peacebuilding, and future cities.',
      img: '/walied.jpg',
      tags: ['Civic AI Architecture', 'Cross-Continental Tech', 'Dubai Hub'],
    },
    accent: '#163B32',
  },
  {
    id: 6,
    region: 'East Africa, Southern Africa & Central Europe',
    shortName: 'Nairobi & Berlin',
    hubs: 'Nairobi & Berlin Hubs',
    city: 'Nairobi, Kenya & Berlin, Germany',
    timezone: 'Africa/Nairobi',
    utcOffset: 'UTC+3',
    code: 'AFR-06',
    lat: -1.2921,
    lng: 36.8219,
    theme: 'Global justice, climate resilience, peace, democracy and ethical governance',
    coordinator: 'Meera',
    producer: {
      name: 'Dr. Lee Kironget',
      role: 'Regional Producer — Africa & Central Europe',
      bio: 'Dr. Lee champions public health innovation, deploying localized diagnostic AI models and planetary governance frameworks across East/Southern Africa and Central Europe (Supported by Brainy).',
      img: '/lee.jpg',
      tags: ['Decentralized Health', 'African NLP', 'Nairobi Hub'],
    },
    accent: '#C96F4A',
  },
  {
    id: 7,
    region: 'UK, Ireland, Iberia & West Africa',
    shortName: 'London',
    hubs: 'London Hub',
    city: 'London, UK',
    timezone: 'Europe/London',
    utcOffset: 'UTC+1',
    code: 'EUR-07',
    lat: 51.5074,
    lng: -0.1278,
    theme: 'Compassionate leadership, responsible innovation, migration and global citizenship',
    coordinator: 'Adithya Baiju',
    producer: {
      name: 'Fabrizio Gramuglio',
      role: 'Regional Producer — UK, Ireland, Iberia & West Africa',
      bio: 'Fabrizio leads European initiatives combining AI and human dignity. Building and advocating the Compassion Economy (Co-Producer: Edith Öller).',
      img: '/fabrizio.jpg',
      tags: ['European AI', 'Digital Ethics', 'London Hub'],
    },
    accent: '#557C8B',
  },
  {
    id: 8,
    region: 'Eastern & Southern South America, Caribbean',
    shortName: 'São Paulo',
    hubs: 'São Paulo Hub',
    city: 'São Paulo, Brazil & Willemstad, Curaçao',
    timezone: 'America/Sao_Paulo',
    utcOffset: 'UTC-3',
    code: 'LATAM-08',
    lat: -23.5505,
    lng: -46.6333,
    theme: 'Biodiversity, Indigenous communities, social innovation and regenerative economies',
    coordinator: 'Adithya Baiju',
    producer: {
      name: 'Julieta Reyes',
      role: 'Regional Producer — Eastern & Southern South America, Caribbean',
      bio: 'Julieta convenes regional innovators and grassroots communities across South America and the Caribbean to bridge indigenous wisdom, environmental resilience, and compassionate regenerative economies.',
      img: '/julieta.jpg',
      tags: ['Indigenous Wisdom', 'Latin American AI', 'São Paulo Hub'],
    },
    accent: '#163B32',
  },
  {
    id: 9,
    region: 'Eastern United States and Southern United States',
    shortName: 'New York',
    hubs: 'New York Hub',
    city: 'New York, USA',
    timezone: 'America/New_York',
    utcOffset: 'UTC-4',
    code: 'USA-09',
    lat: 40.7128,
    lng: -74.006,
    theme: 'Civil rights, democratic participation, global health and youth-led social movements',
    coordinator: 'Meera',
    producer: {
      name: 'Producer Spot Available',
      role: 'Regional Producer — Eastern & Southern United States',
      bio: 'Open convener and regional leadership spot to explore civil rights, democratic participation, global health, and youth-led social movements.',
      img: '',
      tags: ['Civil Rights', 'Democratic AI', 'New York Hub'],
      available: true,
    },
    accent: '#C96F4A',
  },
  {
    id: 10,
    region: 'Midwestern United States & Mexico',
    shortName: 'Chicago & Mexico City',
    hubs: 'Chicago & Mexico City Hubs',
    city: 'Chicago, USA & Mexico City, Mexico',
    timezone: 'America/Chicago',
    utcOffset: 'UTC-5',
    code: 'MEX-10',
    lat: 19.4326,
    lng: -99.1332,
    theme: 'Cross-border collaboration, entrepreneurship, education access and compassionate communities',
    coordinator: 'Niya',
    producer: {
      name: 'Producer Spot Available',
      role: 'Regional Producer — Midwestern US & Mexico',
      bio: 'Open convener and regional leadership spot to explore transformative technology, cross-border collaboration, and compassionate communities.',
      img: '',
      tags: ['Transformative Tech', 'Cultural Heritage', 'Mexico City Hub'],
      available: true,
    },
    accent: '#557C8B',
  },
  {
    id: 11,
    region: 'Western North America',
    shortName: 'Los Angeles',
    hubs: 'Los Angeles Hub',
    city: 'Los Angeles, USA',
    timezone: 'America/Los_Angeles',
    utcOffset: 'UTC-7',
    code: 'USA-11',
    lat: 34.0522,
    lng: -118.2437,
    theme: 'Frontier AI, creativity, entertainment, entrepreneurship and technology with compassion',
    coordinator: 'Ann Rose Mathew',
    producer: {
      name: 'Ani Chahal Honan',
      role: 'Regional Producer — Western North America',
      bio: 'Ani convenes media ethicists, creators, and technologists across Los Angeles, Silicon Valley, and the Pacific Rim exploring frontier AI, creativity, entertainment, and technology with compassion.',
      img: '/ani.jpg',
      tags: ['Frontier AI', 'Creativity & Media', 'Los Angeles Hub'],
    },
    accent: '#163B32',
  },
  {
    id: 12,
    region: 'Hawaiʻi, Alaska & Pacific Islands',
    shortName: 'Honolulu',
    hubs: 'Honolulu Hub',
    city: 'Honolulu, Hawaii',
    timezone: 'Pacific/Honolulu',
    utcOffset: 'UTC-10',
    code: 'PAC-12',
    lat: 21.3069,
    lng: -157.8583,
    theme: 'Ocean consciousness, Indigenous navigation, ecological responsibility & island communities',
    coordinator: 'Niya',
    producer: {
      name: 'Producer Spot Available',
      role: 'Regional Producer — Hawaiʻi, Alaska & Pacific Islands',
      bio: 'Open convener and regional leadership spot to champion island sovereignty and indigenous navigation protocols, guiding global AI ecological stewardship.',
      img: '',
      tags: ['Ocean Sovereignty', 'Community Stewardship', 'Honolulu Hub'],
      available: true,
    },
    accent: '#C9A96A',
  },
];

